# Generated by Django 5.0.14 on 2025-12-23 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'İletişim Bilgisi',
                'verbose_name_plural': 'İletişim Bilgileri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('date_range', models.CharField(help_text='Örn: 2014 - Günümüz', max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Deneyim',
                'verbose_name_plural': 'Deneyimler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Murat Cengiz', max_length=100)),
                ('subtitle', models.CharField(default='Software Developer & Space Enthusiast', max_length=200)),
                ('tagline', models.CharField(default='From Code to Cosmos 🚀', max_length=200)),
                ('about_title', models.CharField(default='6 Yaşında Başlayan Bir Yolculuk', max_length=200)),
                ('about_emoji', models.CharField(default='👨\u200d💻', help_text='Profil resmi yerine geçen emoji', max_length=10)),
                ('about_text', models.TextField(help_text='Paragraflar arası boşluk bırakarak yazınız.')),
                ('footer_text', models.CharField(default='© 2025 Murat Cengiz. Coded with 💙 and ☕', max_length=200)),
            ],
            options={
                'verbose_name': 'Profil Ayarları',
                'verbose_name_plural': 'Profil Ayarları',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Emoji ikonu (örn: 💻)', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Yetenek Kategorisi',
                'verbose_name_plural': 'Yetenek Kategorileri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_app.skillcategory')),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
                'ordering': ['order'],
            },
        ),
    ]
